In [12]:

import numpy as np

In [13]:
matrix1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]],np.int32)

In [14]:
print(matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
a=b=c=d=e=f=g=h=i=1

matrix1 = np.array([[a, b, c],[d, e, f],[g, h, i]],np.int32)
print(matrix1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [29]:
import random
a=random.randrange(0,10,1)
b=random.randrange(0,10,1)
c=random.randrange(0,10,1)
d=random.randrange(0,10,1)
e=random.randrange(0,10,1)
f=random.randrange(0,10,1)
g=random.randrange(0,10,1)
h=random.randrange(0,10,1)
i=random.randrange(0,10,1)
j=random.randrange(0,10,1)
k=random.randrange(0,10,1)
l=random.randrange(0,10,1)
m=random.randrange(0,10,1)
n=random.randrange(0,10,1)
o=random.randrange(0,10,1)
p=random.randrange(0,10,1)
q=random.randrange(0,10,1)
r=random.randrange(0,10,1)


matrix1 = np.array([[a, b, c],[d, e, f],[g, h, i]],np.int32)
matrix2 = np.array([[j, k, l],[m, n, o],[p, q, r]],np.int32)

a1 = a*j+b*m+c*p
b1 = a*k+b*n+c*q
c1 = a*l+b*o+c*r
d1 = d*j+e*m+c*p
e1 = d*k+e*n+f*q
f1 = d*l+e*o+f*r
g1 = g*j+h*m+i*p
h1 = g*k+h*n+i*q
i1 = g*l+h*o+i*r

matrixmulti = np.array([[a1, b1, c1],[d1, e1, f1],[g1, h1, i1]],np.int32)


print('matrix1 = ')
print(matrix1)
print('matrix2 = ')
print(matrix2)
print('matrix1 * matrix2 = ')
print(matrixmulti)



matrix1 = 
[[4 6 6]
 [7 4 8]
 [9 1 0]]
matrix2 = 
[[8 9 3]
 [4 5 7]
 [8 9 5]]
matrix1 * matrix2 = 
[[104 120  84]
 [120 155  89]
 [ 76  86  34]]
